use_frameworks!

platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'WTWifiSDK_Example' do

  pod 'Protobuf'
  pod 'WTWifiSDK', :path => '../'
#    pod 'WTWifiSDK', '~> 1.0.5'
  target 'WTWifiSDK_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
