use_frameworks!

platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'WTWifiSDK_Example' do
  pod 'WTWifiSDK', :path => '../'
#  pod 'WTWifiSDK', '~> 1.0.5'
  target 'WTWifiSDK_Tests' do
    inherit! :search_paths

    
  end
end
